#配置文件
[Web]
model = "release"       #debug  release  test
port = "0.0.0.0:8082"   #服务要运行的端口

[Database]
host = "127.0.0.1"
port = 3306
username = "root"       #数据库账号
password = "root"       #数据库密码
dbname = "ssh"          #数据库名
poolsize = 10           #Mysql连接池大小

[Redis]
host = "127.0.0.1"
port = 6379
password = ""           #没有则不填
poolsize = 10           #Redis连接池大小

[Alisms]
accessid = "—"
accesskey = "-"
signname = "-"  #短信签名
template = "-"  #模板代码